#!/bin/bash
"""
USB Alias Setup Script for In-line Viscometry System
This script creates persistent USB aliases for Arduino and ESP8266 devices

Usage: sudo bash setup_usb_aliases.sh
"""

echo "=================================================="
echo "USB ALIAS SETUP - In-line Viscometry System"
echo "=================================================="
echo

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Error: This script must be run as root"
    echo "Please run: sudo bash setup_usb_aliases.sh"
    exit 1
fi

echo "🔍 Detecting connected USB devices..."
echo

# Show currently connected devices
lsusb | grep -E "(Arduino|2341|1a86|CH340)"

echo
echo "📝 Creating udev rules for persistent device naming..."

# Create udev rules file for viscometry system
RULES_FILE="/etc/udev/rules.d/99-viscometry.rules"

cat > "$RULES_FILE" << 'EOF'
# USB Aliases for In-line Viscometry System
# Generated by setup_usb_aliases.sh

# Arduino Uno (Pump Controller)
# VID:PID = 2341:0043 (Arduino SA Uno R3) 
SUBSYSTEM=="tty", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="0043", SYMLINK+="arduino_pump"

# ESP8266 with CH340 (Flow Sensors - Programming Port)  
# VID:PID = 1a86:7523 (QinHeng Electronics CH340)
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", SYMLINK+="esp8266_sensors"

# Alternative ESP8266 with CP2102 (if using different USB-serial chip)
# VID:PID = 10c4:ea60 (Cygnal Integrated Products CP2102)
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", SYMLINK+="esp8266_sensors_cp2102"

# Set permissions for dialout group access
SUBSYSTEM=="tty", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="0043", MODE="0666", GROUP="dialout"
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", MODE="0666", GROUP="dialout"
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE="0666", GROUP="dialout"
EOF

echo "✅ Created udev rules: $RULES_FILE"
echo

# Show the created rules
echo "📋 Udev rules content:"
cat "$RULES_FILE"
echo

# Reload udev rules
echo "🔄 Reloading udev rules..."
udevadm control --reload-rules
udevadm trigger

echo "✅ Udev rules reloaded"
echo

# Check if devices are connected and show expected aliases
echo "🔍 Checking for USB aliases..."
echo

if [ -e "/dev/arduino_pump" ]; then
    echo "✅ Arduino alias found: /dev/arduino_pump -> $(realpath /dev/arduino_pump)"
else
    echo "⚠️  Arduino alias not found: /dev/arduino_pump"
    echo "   Connect Arduino Uno via USB to create this alias"
fi

if [ -e "/dev/esp8266_sensors" ]; then
    echo "✅ ESP8266 alias found: /dev/esp8266_sensors -> $(realpath /dev/esp8266_sensors)"
else
    echo "⚠️  ESP8266 alias not found: /dev/esp8266_sensors"
    echo "   Connect ESP8266 with CH340 chip via USB to create this alias"
fi

if [ -e "/dev/esp8266_sensors_cp2102" ]; then
    echo "✅ ESP8266 CP2102 alias found: /dev/esp8266_sensors_cp2102 -> $(realpath /dev/esp8266_sensors_cp2102)"
fi

echo
echo "=================================================="
echo "USB ALIAS SETUP COMPLETE"
echo "=================================================="
echo
echo "✨ Benefits:"
echo "   • /dev/arduino_pump always points to Arduino Uno"
echo "   • /dev/esp8266_sensors always points to ESP8266"
echo "   • No more changing /dev/ttyACM0, /dev/ttyUSB0 device names"
echo "   • Reliable device identification in production"
echo
echo "🔧 Usage:"
echo "   • Program ESP8266: Connect via /dev/esp8266_sensors"
echo "   • Arduino communication: System uses /dev/arduino_pump"
echo "   • Web interface: http://192.168.10.200"
echo
echo "🚀 Ready to start viscometry system:"
echo "   python3 start_system.py"
echo